import { Palette } from "./palette"

export const ColorLight = {
    Background             : `var(--md-sys-color-background, ${Palette.Neutral98})`,
    Error                  : `var(--md-sys-color-error, ${Palette.Error40})`,
    ErrorContainer         : `var(--md-sys-color-error-container, ${Palette.Error90})`,
    InverseOnSurface       : `var(--md-sys-color-inverse-on-surface, ${Palette.Neutral95})`,
    InversePrimary         : `var(--md-sys-color-inverse-primary, ${Palette.Primary80})`,
    InverseSurface         : `var(--md-sys-color-inverse-surface, ${Palette.Neutral20})`,
    OnBackground           : `var(--md-sys-color-on-background, ${Palette.Neutral10})`,
    OnError                : `var(--md-sys-color-on-error, ${Palette.Error100})`,
    OnErrorContainer       : `var(--md-sys-color-on-error-container, ${Palette.Error10})`,
    OnPrimary              : `var(--md-sys-color-on-primary, ${Palette.Primary100})`,
    OnPrimaryContainer     : `var(--md-sys-color-on-primary-container, ${Palette.Primary10})`,
    OnPrimaryFixed         : `var(--md-sys-color-on-primary-fixed, ${Palette.Primary10})`,
    OnPrimaryFixedVariant  : `var(--md-sys-color-on-primary-fixed-variant, ${Palette.Primary30})`,
    OnSecondary            : `var(--md-sys-color-on-secondary, ${Palette.Secondary100})`,
    OnSecondaryContainer   : `var(--md-sys-color-on-secondary-container, ${Palette.Secondary10})`,
    OnSecondaryFixed       : `var(--md-sys-color-on-secondary-fixed, ${Palette.Secondary10})`,
    OnSecondaryFixedVariant: `var(--md-sys-color-on-secondary-fixed-variant, ${Palette.Secondary30})`,
    OnSurface              : `var(--md-sys-color-on-surface, ${Palette.Neutral10})`,
    OnSurfaceVariant       : `var(--md-sys-color-on-surface-variant, ${Palette.NeutralVariant30})`,
    OnTertiary             : `var(--md-sys-color-on-tertiary, ${Palette.Tertiary100})`,
    OnTertiaryContainer    : `var(--md-sys-color-on-tertiary-container, ${Palette.Tertiary10})`,
    OnTertiaryFixed        : `var(--md-sys-color-on-tertiary-fixed, ${Palette.Tertiary10})`,
    OnTertiaryFixedVariant : `var(--md-sys-color-on-tertiary-fixed-variant, ${Palette.Tertiary30})`,
    Outline                : `var(--md-sys-color-outline, ${Palette.Neutral50})`,
    OutlineVariant         : `var(--md-sys-color-outline-variant, ${Palette.NeutralVariant80})`,
    Primary                : `var(--md-sys-color-primary, ${Palette.Primary40})`,
    PrimaryContainer       : `var(--md-sys-color-primary-container, ${Palette.Primary90})`,
    PrimaryFixed           : `var(--md-sys-color-primary-fixed, ${Palette.Primary90})`,
    PrimaryFixedDim        : `var(--md-sys-color-primary-fixed-dim, ${Palette.Primary80})`,
    Scrim                  : `var(--md-sys-color-scrim, ${Palette.Neutral0})`,
    Secondary              : `var(--md-sys-color-secondary, ${Palette.Secondary40})`,
    SecondaryContainer     : `var(--md-sys-color-secondary-container, ${Palette.Secondary90})`,
    SecondaryFixed         : `var(--md-sys-color-secondary-fixed, ${Palette.Secondary90})`,
    SecondaryFixedDim      : `var(--md-sys-color-secondary-fixed-dim, ${Palette.Secondary80})`,
    Shadow                 : `var(--md-sys-color-shadow, ${Palette.Neutral0})`,
    Surface                : `var(--md-sys-color-surface, ${Palette.Neutral98})`,
    SurfaceBright          : `var(--md-sys-color-surface-bright, ${Palette.Neutral98})`,
    SurfaceContainer       : `var(--md-sys-color-surface-container, ${Palette.Neutral94})`,
    SurfaceContainerHigh   : `var(--md-sys-color-surface-container-high, ${Palette.Neutral92})`,
    SurfaceContainerHighest: `var(--md-sys-color-surface-container-highest, ${Palette.Neutral90})`,
    SurfaceContainerLow    : `var(--md-sys-color-surface-container-low, ${Palette.Neutral96})`,
    SurfaceContainerLowest : `var(--md-sys-color-surface-container-lowest, ${Palette.Neutral100})`,
    SurfaceDim             : `var(--md-sys-color-surface-dim, ${Palette.Neutral87})`,
    SurfaceTint            : `var(--md-sys-color-surface-tint, ${Palette.Primary40})`,
    SurfaceVariant         : `var(--md-sys-color-surface-variant, ${Palette.NeutralVariant90})`,
    Tertiary               : `var(--md-sys-color-tertiary, ${Palette.Tertiary40})`,
    TertiaryContainer      : `var(--md-sys-color-tertiary-container, ${Palette.Tertiary90})`,
    TertiaryFixed          : `var(--md-sys-color-tertiary-fixed, ${Palette.Tertiary90})`,
    TertiaryFixedDim       : `var(--md-sys-color-tertiary-fixed-dim, ${Palette.Tertiary80})`,
} as const

export const ColorDark = {
    Background             : `var(--md-sys-color-background, ${Palette.Neutral6})`,
    Error                  : `var(--md-sys-color-error, ${Palette.Error80})`,
    ErrorContainer         : `var(--md-sys-color-error-container, ${Palette.Error30})`,
    InverseOnSurface       : `var(--md-sys-color-inverse-on-surface, ${Palette.Neutral20})`,
    InversePrimary         : `var(--md-sys-color-inverse-primary, ${Palette.Primary40})`,
    InverseSurface         : `var(--md-sys-color-inverse-surface, ${Palette.Neutral90})`,
    OnBackground           : `var(--md-sys-color-on-background, ${Palette.Neutral90})`,
    OnError                : `var(--md-sys-color-on-error, ${Palette.Error20})`,
    OnErrorContainer       : `var(--md-sys-color-on-error-container, ${Palette.Error90})`,
    OnPrimary              : `var(--md-sys-color-on-primary, ${Palette.Primary20})`,
    OnPrimaryContainer     : `var(--md-sys-color-on-primary-container, ${Palette.Primary90})`,
    OnPrimaryFixed         : `var(--md-sys-color-on-primary-fixed, ${Palette.Primary10})`,
    OnPrimaryFixedVariant  : `var(--md-sys-color-on-primary-fixed-variant, ${Palette.Primary30})`,
    OnSecondary            : `var(--md-sys-color-on-secondary, ${Palette.Secondary20})`,
    OnSecondaryContainer   : `var(--md-sys-color-on-secondary-container, ${Palette.Secondary90})`,
    OnSecondaryFixed       : `var(--md-sys-color-on-secondary-fixed, ${Palette.Secondary10})`,
    OnSecondaryFixedVariant: `var(--md-sys-color-on-secondary-fixed-variant, ${Palette.Secondary30})`,
    OnSurface              : `var(--md-sys-color-on-surface, ${Palette.Neutral90})`,
    OnSurfaceVariant       : `var(--md-sys-color-on-surface-variant, ${Palette.NeutralVariant80})`,
    OnTertiary             : `var(--md-sys-color-on-tertiary, ${Palette.Tertiary20})`,
    OnTertiaryContainer    : `var(--md-sys-color-on-tertiary-container, ${Palette.Tertiary90})`,
    OnTertiaryFixed        : `var(--md-sys-color-on-tertiary-fixed, ${Palette.Tertiary10})`,
    OnTertiaryFixedVariant : `var(--md-sys-color-on-tertiary-fixed-variant, ${Palette.Tertiary30})`,
    Outline                : `var(--md-sys-color-outline, ${Palette.Neutral60})`,
    OutlineVariant         : `var(--md-sys-color-outline-variant, ${Palette.NeutralVariant30})`,
    Primary                : `var(--md-sys-color-primary, ${Palette.Primary80})`,
    PrimaryContainer       : `var(--md-sys-color-primary-container, ${Palette.Primary30})`,
    PrimaryFixed           : `var(--md-sys-color-primary-fixed, ${Palette.Primary90})`,
    PrimaryFixedDim        : `var(--md-sys-color-primary-fixed-dim, ${Palette.Primary80})`,
    Scrim                  : `var(--md-sys-color-scrim, ${Palette.Neutral0})`,
    Secondary              : `var(--md-sys-color-secondary, ${Palette.Secondary80})`,
    SecondaryContainer     : `var(--md-sys-color-secondary-container, ${Palette.Secondary30})`,
    SecondaryFixed         : `var(--md-sys-color-secondary-fixed, ${Palette.Secondary90})`,
    SecondaryFixedDim      : `var(--md-sys-color-secondary-fixed-dim, ${Palette.Secondary80})`,
    Shadow                 : `var(--md-sys-color-shadow, ${Palette.Neutral0})`,
    Surface                : `var(--md-sys-color-surface, ${Palette.Neutral6})`,
    SurfaceBright          : `var(--md-sys-color-surface-bright, ${Palette.Neutral24})`,
    SurfaceContainer       : `var(--md-sys-color-surface-container, ${Palette.Neutral12})`,
    SurfaceContainerHigh   : `var(--md-sys-color-surface-container-high, ${Palette.Neutral17})`,
    SurfaceContainerHighest: `var(--md-sys-color-surface-container-highest, ${Palette.Neutral22})`,
    SurfaceContainerLow    : `var(--md-sys-color-surface-container-low, ${Palette.Neutral10})`,
    SurfaceContainerLowest : `var(--md-sys-color-surface-container-lowest, ${Palette.Neutral4})`,
    SurfaceDim             : `var(--md-sys-color-surface-dim, ${Palette.Neutral6})`,
    SurfaceTint            : `var(--md-sys-color-surface-tint, ${Palette.Primary80})`,
    SurfaceVariant         : `var(--md-sys-color-surface-variant, ${Palette.NeutralVariant30})`,
    Tertiary               : `var(--md-sys-color-tertiary, ${Palette.Tertiary80})`,
    TertiaryContainer      : `var(--md-sys-color-tertiary-container, ${Palette.Tertiary30})`,
    TertiaryFixed          : `var(--md-sys-color-tertiary-fixed, ${Palette.Tertiary90})`,
    TertiaryFixedDim       : `var(--md-sys-color-tertiary-fixed-dim, ${Palette.Tertiary80})`,
} as const

export const Color = {
    Background             : `var(--md-sys-color-background, light-dark(${Palette.Neutral98}, ${Palette.Neutral6}))`,
    Error                  : `var(--md-sys-color-error, light-dark(${Palette.Error40}, ${Palette.Error80}))`,
    ErrorContainer         : `var(--md-sys-color-error-container, light-dark(${Palette.Error90}, ${Palette.Error30}))`,
    InverseOnSurface       : `var(--md-sys-color-inverse-on-surface, light-dark(${Palette.Neutral95}, ${Palette.Neutral20}))`,
    InversePrimary         : `var(--md-sys-color-inverse-primary, light-dark(${Palette.Primary80}, ${Palette.Primary40}))`,
    InverseSurface         : `var(--md-sys-color-inverse-surface, light-dark(${Palette.Neutral20}, ${Palette.Neutral90}))`,
    OnBackground           : `var(--md-sys-color-on-background, light-dark(${Palette.Neutral10}, ${Palette.Neutral90}))`,
    OnError                : `var(--md-sys-color-on-error, light-dark(${Palette.Error100}, ${Palette.Error20}))`,
    OnErrorContainer       : `var(--md-sys-color-on-error-container, light-dark(${Palette.Error10}, ${Palette.Error90}))`,
    OnPrimary              : `var(--md-sys-color-on-primary, light-dark(${Palette.Primary100}, ${Palette.Primary20}))`,
    OnPrimaryContainer     : `var(--md-sys-color-on-primary-container, light-dark(${Palette.Primary10}, ${Palette.Primary90}))`,
    OnPrimaryFixed         : `var(--md-sys-color-on-primary-fixed, light-dark(${Palette.Primary10}, ${Palette.Primary10}))`,
    OnPrimaryFixedVariant  : `var(--md-sys-color-on-primary-fixed-variant, light-dark(${Palette.Primary30}, ${Palette.Primary30}))`,
    OnSecondary            : `var(--md-sys-color-on-secondary, light-dark(${Palette.Secondary100}, ${Palette.Secondary20}))`,
    OnSecondaryContainer   : `var(--md-sys-color-on-secondary-container, light-dark(${Palette.Secondary10}, ${Palette.Secondary90}))`,
    OnSecondaryFixed       : `var(--md-sys-color-on-secondary-fixed, light-dark(${Palette.Secondary10}, ${Palette.Secondary10}))`,
    OnSecondaryFixedVariant: `var(--md-sys-color-on-secondary-fixed-variant, light-dark(${Palette.Secondary30}, ${Palette.Secondary30}))`,
    OnSurface              : `var(--md-sys-color-on-surface, light-dark(${Palette.Neutral10}, ${Palette.Neutral90}))`,
    OnSurfaceVariant       : `var(--md-sys-color-on-surface-variant, light-dark(${Palette.NeutralVariant30}, ${Palette.NeutralVariant80}))`,
    OnTertiary             : `var(--md-sys-color-on-tertiary, light-dark(${Palette.Tertiary100}, ${Palette.Tertiary20}))`,
    OnTertiaryContainer    : `var(--md-sys-color-on-tertiary-container, light-dark(${Palette.Tertiary10}, ${Palette.Tertiary90}))`,
    OnTertiaryFixed        : `var(--md-sys-color-on-tertiary-fixed, light-dark(${Palette.Tertiary10}, ${Palette.Tertiary10}))`,
    OnTertiaryFixedVariant : `var(--md-sys-color-on-tertiary-fixed-variant, light-dark(${Palette.Tertiary30}, ${Palette.Tertiary30}))`,
    Outline                : `var(--md-sys-color-outline, light-dark(${Palette.Neutral50}, ${Palette.Neutral60}))`,
    OutlineVariant         : `var(--md-sys-color-outline-variant, light-dark(${Palette.NeutralVariant80}, ${Palette.NeutralVariant30}))`,
    Primary                : `var(--md-sys-color-primary, light-dark(${Palette.Primary40}, ${Palette.Primary80}))`,
    PrimaryContainer       : `var(--md-sys-color-primary-container, light-dark(${Palette.Primary90}, ${Palette.Primary30}))`,
    PrimaryFixed           : `var(--md-sys-color-primary-fixed, light-dark(${Palette.Primary90}, ${Palette.Primary90}))`,
    PrimaryFixedDim        : `var(--md-sys-color-primary-fixed-dim, light-dark(${Palette.Primary80}, ${Palette.Primary80}))`,
    Scrim                  : `var(--md-sys-color-scrim, light-dark(${Palette.Neutral0}, ${Palette.Neutral0}))`,
    Secondary              : `var(--md-sys-color-secondary, light-dark(${Palette.Secondary40}, ${Palette.Secondary80}))`,
    SecondaryContainer     : `var(--md-sys-color-secondary-container, light-dark(${Palette.Secondary90}, ${Palette.Secondary30}))`,
    SecondaryFixed         : `var(--md-sys-color-secondary-fixed, light-dark(${Palette.Secondary90}, ${Palette.Secondary90}))`,
    SecondaryFixedDim      : `var(--md-sys-color-secondary-fixed-dim, light-dark(${Palette.Secondary80}, ${Palette.Secondary80}))`,
    Shadow                 : `var(--md-sys-color-shadow, light-dark(${Palette.Neutral0}, ${Palette.Neutral0}))`,
    Surface                : `var(--md-sys-color-surface, light-dark(${Palette.Neutral98}, ${Palette.Neutral6}))`,
    SurfaceBright          : `var(--md-sys-color-surface-bright, light-dark(${Palette.Neutral98}, ${Palette.Neutral24}))`,
    SurfaceContainer       : `var(--md-sys-color-surface-container, light-dark(${Palette.Neutral94}, ${Palette.Neutral12}))`,
    SurfaceContainerHigh   : `var(--md-sys-color-surface-container-high, light-dark(${Palette.Neutral92}, ${Palette.Neutral17}))`,
    SurfaceContainerHighest: `var(--md-sys-color-surface-container-highest, light-dark(${Palette.Neutral90}, ${Palette.Neutral22}))`,
    SurfaceContainerLow    : `var(--md-sys-color-surface-container-low, light-dark(${Palette.Neutral96}, ${Palette.Neutral10}))`,
    SurfaceContainerLowest : `var(--md-sys-color-surface-container-lowest, light-dark(${Palette.Neutral100}, ${Palette.Neutral4}))`,
    SurfaceDim             : `var(--md-sys-color-surface-dim, light-dark(${Palette.Neutral87}, ${Palette.Neutral6}))`,
    SurfaceTint            : `var(--md-sys-color-surface-tint, light-dark(${Palette.Primary40}, ${Palette.Primary80}))`,
    SurfaceVariant         : `var(--md-sys-color-surface-variant, light-dark(${Palette.NeutralVariant90}, ${Palette.NeutralVariant30}))`,
    Tertiary               : `var(--md-sys-color-tertiary, light-dark(${Palette.Tertiary40}, ${Palette.Tertiary80}))`,
    TertiaryContainer      : `var(--md-sys-color-tertiary-container, light-dark(${Palette.Tertiary90}, ${Palette.Tertiary30}))`,
    TertiaryFixed          : `var(--md-sys-color-tertiary-fixed, light-dark(${Palette.Tertiary90}, ${Palette.Tertiary90}))`,
    TertiaryFixedDim       : `var(--md-sys-color-tertiary-fixed-dim, light-dark(${Palette.Tertiary80}, ${Palette.Tertiary80}))`,
} as const