import type { SemanticColorNames } from "../interfaces/semantic-color-names.interface";

export const DefaultColorContract = {
    PrimaryKeyColor        : { key: `--md-sys-color-primary-key-color`,          value: `#039d54`},
    SecondaryKeyColor      : { key: `--md-sys-color-secondary-key-color`,        value: `#54815f`},
    TertiaryKeyColor       : { key: `--md-sys-color-tertiary-key-color`,         value: `#ffa97f`},
    ErrorKeyColor          : { key: `--md-sys-color-error-key-color`,            value: `#de3730`},
    NeutralKeyColor        : { key: `--md-sys-color-neutral-key-color`,          value: `#727971`},
    NeutralVariantKeyColor : { key: `--md-sys-color-neutral-variant-key-color`,  value: `#6d7a6e`},
    Background             : { key: `--md-sys-color-background`,                 value: `light-dark(#f4fbf1, #0e150f)`},
    Error                  : { key: `--md-sys-color-error`,                      value: `light-dark(#ba1a1a, #ffb4ab)`},
    ErrorContainer         : { key: `--md-sys-color-error-container`,            value: `light-dark(#ffdad6, #93000a)`},
    ErrorDim               : { key: `--md-sys-color-error-dim`,                  value: `light-dark(#a80710, #ff554a)`},
    InverseOnSurface       : { key: `--md-sys-color-inverse-on-surface`,         value: `light-dark(#ecf3e9, #2b322c)`},
    InversePrimary         : { key: `--md-sys-color-inverse-primary`,            value: `light-dark(#61de8c, #006d38)`},
    InverseSurface         : { key: `--md-sys-color-inverse-surface`,            value: `light-dark(#2b322c, #dde4db)`},
    OnBackground           : { key: `--md-sys-color-on-background`,              value: `light-dark(#171d17, #dde4db)`},
    OnError                : { key: `--md-sys-color-on-error`,                   value: `light-dark(#ffffff, #690005)`},
    OnErrorContainer       : { key: `--md-sys-color-on-error-container`,         value: `light-dark(#93000a, #ffdad6)`},
    OnPrimary              : { key: `--md-sys-color-on-primary`,                 value: `light-dark(#ffffff, #00391a)`},
    OnPrimaryContainer     : { key: `--md-sys-color-on-primary-container`,       value: `light-dark(#00592c, #00592c)`},
    OnPrimaryFixed         : { key: `--md-sys-color-on-primary-fixed`,           value: `light-dark(#00210d, #00210d)`},
    OnPrimaryFixedVariant  : { key: `--md-sys-color-on-primary-fixed-variant`,   value: `light-dark(#005229, #005229)`},
    OnSecondary            : { key: `--md-sys-color-on-secondary`,               value: `light-dark(#ffffff, #0a381c)`},
    OnSecondaryContainer   : { key: `--md-sys-color-on-secondary-container`,     value: `light-dark(#406c4b, #97c7a0)`},
    OnSecondaryFixed       : { key: `--md-sys-color-on-secondary-fixed`,         value: `light-dark(#00210d, #00210d)`},
    OnSecondaryFixedVariant: { key: `--md-sys-color-on-secondary-fixed-variant`, value: `light-dark(#244f31, #244f31)`},
    OnSurface              : { key: `--md-sys-color-on-surface`,                 value: `light-dark(#171d17, #dde4db)`},
    OnSurfaceVariant       : { key: `--md-sys-color-on-surface-variant`,         value: `light-dark(#3d4a3f, #bccabc)`},
    OnTertiary             : { key: `--md-sys-color-on-tertiary`,                value: `light-dark(#ffffff, #552002)`},
    OnTertiaryContainer    : { key: `--md-sys-color-on-tertiary-container`,      value: `light-dark(#793c1a, #793c1a)`},
    OnTertiaryFixed        : { key: `--md-sys-color-on-tertiary-fixed`,          value: `light-dark(#351000, #351000)`},
    OnTertiaryFixedVariant : { key: `--md-sys-color-on-tertiary-fixed-variant`,  value: `light-dark(#723615, #723615)`},
    Outline                : { key: `--md-sys-color-outline`,                    value: `light-dark(#6d7a6e, #879487)`},
    OutlineVariant         : { key: `--md-sys-color-outline-variant`,            value: `light-dark(#bccabc, #3d4a3f)`},
    Primary                : { key: `--md-sys-color-primary`,                    value: `light-dark(#006d38, #76f29e)`},
    PrimaryContainer       : { key: `--md-sys-color-primary-container`,          value: `light-dark(#58d584, #58d584)`},
    PrimaryDim             : { key: `--md-sys-color-primary-dim`,                value: `light-dark(#006030, #82fea8)`},
    PrimaryFixed           : { key: `--md-sys-color-primary-fixed`,              value: `light-dark(#7ffba6, #7ffba6)`},
    PrimaryFixedDim        : { key: `--md-sys-color-primary-fixed-dim`,          value: `light-dark(#61de8c, #61de8c)`},
    Scrim                  : { key: `--md-sys-color-scrim`,                      value: `light-dark(#000000, #000000)`},
    Secondary              : { key: `--md-sys-color-secondary`,                  value: `light-dark(#3c6847, #a2d2ab)`},
    SecondaryContainer     : { key: `--md-sys-color-secondary-container`,        value: `light-dark(#bbecc3, #295436)`},
    SecondaryDim           : { key: `--md-sys-color-secondary-dim`,              value: `light-dark(#305b3c, #bdeec5)`},
    SecondaryFixed         : { key: `--md-sys-color-secondary-fixed`,            value: `light-dark(#bdeec5, #bdeec5)`},
    SecondaryFixedDim      : { key: `--md-sys-color-secondary-fixed-dim`,        value: `light-dark(#a2d2ab, #a2d2ab)`},
    Shadow                 : { key: `--md-sys-color-shadow`,                     value: `light-dark(#000000, #000000)`},
    Surface                : { key: `--md-sys-color-surface`,                    value: `light-dark(#f4fbf1, #0e150f)`},
    SurfaceBright          : { key: `--md-sys-color-surface-bright`,             value: `light-dark(#f4fbf1, #343b34)`},
    SurfaceContainer       : { key: `--md-sys-color-surface-container`,          value: `light-dark(#e9f0e6, #1b211b)`},
    SurfaceContainerHigh   : { key: `--md-sys-color-surface-container-high`,     value: `light-dark(#e3eae1, #252c25)`},
    SurfaceContainerHighest: { key: `--md-sys-color-surface-container-highest`,  value: `light-dark(#dde4db, #303630)`},
    SurfaceContainerLow    : { key: `--md-sys-color-surface-container-low`,      value: `light-dark(#eff6ec, #171d17)`},
    SurfaceContainerLowest : { key: `--md-sys-color-surface-container-lowest`,   value: `light-dark(#ffffff, #09100a)`},
    SurfaceDim             : { key: `--md-sys-color-surface-dim`,                value: `light-dark(#d5dcd3, #0e150f)`},
    SurfaceTint            : { key: `--md-sys-color-surface-tint`,               value: `light-dark(#006d38, #61de8c)`},
    SurfaceVariant         : { key: `--md-sys-color-surface-variant`,            value: `light-dark(#d8e6d7, #3d4a3f)`},
    Tertiary               : { key: `--md-sys-color-tertiary`,                   value: `light-dark(#8f4d2a, #ffcfba)`},
    TertiaryContainer      : { key: `--md-sys-color-tertiary-container`,         value: `light-dark(#ffa97f, #ffa97f)`},
    TertiaryDim            : { key: `--md-sys-color-tertiary-dim`,               value: `light-dark(#804120, #fda77d)`},
    TertiaryFixed          : { key: `--md-sys-color-tertiary-fixed`,             value: `light-dark(#ffdbcc, #ffdbcc)`},
    TertiaryFixedDim       : { key: `--md-sys-color-tertiary-fixed-dim`,         value: `light-dark(#ffb693, #ffb693)`},
} as const satisfies Record<SemanticColorNames, { key: string, value: string }>
