export type { ICSSDeclaration } from './interfaces/css-declaration.interface'
export * from './domain/color'
export * from './domain/contrast-level'
export * from './domain/duration'
export * from './domain/easing'
export * from './domain/elevation'
export * from './domain/shape'
export * from './domain/spacing'
export * from './domain/state'
export * from './domain/palette'
export * from './domain/typeface'
export * from './domain/typescale'
export * from './domain/variant'
