import { DefaultLightColors, Palettes } from "./modules/color";
import { ElevationDps } from "./modules/elevation";
import { MotionDurations, MotionEasings } from "./modules/motion";
import { Shapes } from "./modules/shape";


const motion = {
    short1: MotionDurations.Short1,
    short2: MotionDurations.Short2,
    short3: MotionDurations.Short3,
    short4: MotionDurations.Short4,
    medium1: MotionDurations.Medium1,
    medium2: MotionDurations.Medium2,
    medium3: MotionDurations.Medium3,
    medium4: MotionDurations.Medium4,
    long1: MotionDurations.Long1,
    long2: MotionDurations.Long2,
    long3: MotionDurations.Long3,
    long4: MotionDurations.Long4,
    extraLong1: MotionDurations.ExtraLong1,
    extraLong2: MotionDurations.ExtraLong2,
    extraLong3: MotionDurations.ExtraLong3,
    extraLong4: MotionDurations.ExtraLong4,
} as const

const easing = {
    standard: MotionEasings.Standard,
    standardAccelerate: MotionEasings.StandardAccelerate,
    standardDecelerate: MotionEasings.StandardDecelerate,
    emphasized: MotionEasings.Emphasized,
    emphasizedAccelerate: MotionEasings.EmphasizedAccelerate,
    emphasizedDecelerate: MotionEasings.EmphasizedDecelerate,
    legacy: MotionEasings.Legacy,
    legacyAccelerate: MotionEasings.LegacyAccelerate,
    legacyDecelerate: MotionEasings.LegacyDecelerate,
    linear: MotionEasings.Linear,
} as const

const elevation = {
    level0: ElevationDps.Level0,
    level1: ElevationDps.Level1,
    level2: ElevationDps.Level2,
    level3: ElevationDps.Level3,
    level4: ElevationDps.Level4,
    level5: ElevationDps.Level5,
} as const

const shape = {
    full: Shapes.Full,
    extraLarge: Shapes.ExtraLarge,
    large: Shapes.Large,
    medium: Shapes.Medium,
    small: Shapes.Small,
    extraSmall: Shapes.ExtraSmall,
    none: Shapes.None,
} as const

const palette = {
    black: Palettes.Black,
    error0: Palettes.Error0,
    error10: Palettes.Error10,
    error100: Palettes.Error100,
    error20: Palettes.Error20,
    error30: Palettes.Error30,
    error40: Palettes.Error40,
    error50: Palettes.Error50,
    error60: Palettes.Error60,
    error70: Palettes.Error70,
    error80: Palettes.Error80,
    error90: Palettes.Error90,
    error95: Palettes.Error95,
    error99: Palettes.Error99,
    neutralVariant0: Palettes.NeutralVariant0,
    neutralVariant10: Palettes.NeutralVariant10,
    neutralVariant100: Palettes.NeutralVariant100,
    neutralVariant20: Palettes.NeutralVariant20,
    neutralVariant30: Palettes.NeutralVariant30,
    neutralVariant40: Palettes.NeutralVariant40,
    neutralVariant50: Palettes.NeutralVariant50,
    neutralVariant60: Palettes.NeutralVariant60,
    neutralVariant70: Palettes.NeutralVariant70,
    neutralVariant80: Palettes.NeutralVariant80,
    neutralVariant90: Palettes.NeutralVariant90,
    neutralVariant95: Palettes.NeutralVariant95,
    neutralVariant99: Palettes.NeutralVariant99,
    neutral0: Palettes.Neutral0,
    neutral10: Palettes.Neutral10,
    neutral100: Palettes.Neutral100,
    neutral12: Palettes.Neutral12,
    neutral17: Palettes.Neutral17,
    neutral20: Palettes.Neutral20,
    neutral22: Palettes.Neutral22,
    neutral24: Palettes.Neutral24,
    neutral30: Palettes.Neutral30,
    neutral4: Palettes.Neutral4,
    neutral40: Palettes.Neutral40,
    neutral50: Palettes.Neutral50,
    neutral6: Palettes.Neutral6,
    neutral60: Palettes.Neutral60,
    neutral70: Palettes.Neutral70,
    neutral80: Palettes.Neutral80,
    neutral87: Palettes.Neutral87,
    neutral90: Palettes.Neutral90,
    neutral92: Palettes.Neutral92,
    neutral94: Palettes.Neutral94,
    neutral95: Palettes.Neutral95,
    neutral96: Palettes.Neutral96,
    neutral98: Palettes.Neutral98,
    neutral99: Palettes.Neutral99,
    primary0: Palettes.Primary0,
    primary10: Palettes.Primary10,
    primary100: Palettes.Primary100,
    primary20: Palettes.Primary20,
    primary30: Palettes.Primary30,
    primary40: Palettes.Primary40,
    primary50: Palettes.Primary50,
    primary60: Palettes.Primary60,
    primary70: Palettes.Primary70,
    primary80: Palettes.Primary80,
    primary90: Palettes.Primary90,
    primary95: Palettes.Primary95,
    primary99: Palettes.Primary99,
    secondary0: Palettes.Secondary0,
    secondary10: Palettes.Secondary10,
    secondary100: Palettes.Secondary100,
    secondary20: Palettes.Secondary20,
    secondary30: Palettes.Secondary30,
    secondary40: Palettes.Secondary40,
    secondary50: Palettes.Secondary50,
    secondary60: Palettes.Secondary60,
    secondary70: Palettes.Secondary70,
    secondary80: Palettes.Secondary80,
    secondary90: Palettes.Secondary90,
    secondary95: Palettes.Secondary95,
    secondary99: Palettes.Secondary99,
    tertiary0: Palettes.Tertiary0,
    tertiary10: Palettes.Tertiary10,
    tertiary100: Palettes.Tertiary100,
    tertiary20: Palettes.Tertiary20,
    tertiary30: Palettes.Tertiary30,
    tertiary40: Palettes.Tertiary40,
    tertiary50: Palettes.Tertiary50,
    tertiary60: Palettes.Tertiary60,
    tertiary70: Palettes.Tertiary70,
    tertiary80: Palettes.Tertiary80,
    tertiary90: Palettes.Tertiary90,
    tertiary95: Palettes.Tertiary95,
    tertiary99: Palettes.Tertiary99,
    white: Palettes.White,
} as const

const color = {
    background: DefaultLightColors.Background,
    error: DefaultLightColors.Error,
    errorContainer: DefaultLightColors.ErrorContainer,
    inverseOnSurface: DefaultLightColors.InverseOnSurface,
    inversePrimary: DefaultLightColors.InversePrimary,
    inverseSurface: DefaultLightColors.InverseSurface,
    onBackground: DefaultLightColors.OnBackground,
    onError: DefaultLightColors.OnError,
    onErrorContainer: DefaultLightColors.OnErrorContainer,
    onPrimary: DefaultLightColors.OnPrimary,
    onPrimaryContainer: DefaultLightColors.OnPrimaryContainer,
    onPrimaryFixed: DefaultLightColors.OnPrimaryFixed,
    onPrimaryFixedVariant: DefaultLightColors.OnPrimaryFixedVariant,
    onSecondary: DefaultLightColors.OnSecondary,
    onSecondaryContainer: DefaultLightColors.OnSecondaryContainer,
    onSecondaryFixed: DefaultLightColors.OnSecondaryFixed,
    onSecondaryFixedVariant: DefaultLightColors.OnSecondaryFixedVariant,
    onSurface: DefaultLightColors.OnSurface,
    onSurfaceVariant: DefaultLightColors.OnSurfaceVariant,
    onTertiary: DefaultLightColors.OnTertiary,
    onTertiaryContainer: DefaultLightColors.OnTertiaryContainer,
    onTertiaryFixed: DefaultLightColors.OnTertiaryFixed,
    onTertiaryFixedVariant: DefaultLightColors.OnTertiaryFixedVariant,
    outline: DefaultLightColors.Outline,
    outlineVariant: DefaultLightColors.OutlineVariant,
    primary: DefaultLightColors.Primary,
    primaryContainer: DefaultLightColors.PrimaryContainer,
    primaryFixed: DefaultLightColors.PrimaryFixed,
    primaryFixedDim: DefaultLightColors.PrimaryFixedDim,
    scrim: DefaultLightColors.Scrim,
    secondary: DefaultLightColors.Secondary,
    secondaryContainer: DefaultLightColors.SecondaryContainer,
    secondaryFixed: DefaultLightColors.SecondaryFixed,
    secondaryFixedDim: DefaultLightColors.SecondaryFixedDim,
    shadow: DefaultLightColors.Shadow,
    surface: DefaultLightColors.Surface,
    surfaceBright: DefaultLightColors.SurfaceBright,
    surfaceContainer: DefaultLightColors.SurfaceContainer,
    surfaceContainerHigh: DefaultLightColors.SurfaceContainerHigh,
    surfaceContainerHighest: DefaultLightColors.SurfaceContainerHighest,
    surfaceContainerLow: DefaultLightColors.SurfaceContainerLow,
    surfaceContainerLowest: DefaultLightColors.SurfaceContainerLowest,
    surfaceDim: DefaultLightColors.SurfaceDim,
    surfaceTint: DefaultLightColors.SurfaceTint,
    surfaceVariant: DefaultLightColors.SurfaceVariant,
    tertiary: DefaultLightColors.Tertiary,
    tertiaryContainer: DefaultLightColors.TertiaryContainer,
    tertiaryFixed: DefaultLightColors.TertiaryFixed,
    tertiaryFixedDim: DefaultLightColors.TertiaryFixedDim,
} as const

export const md = {
    sys: {
        color,
        palette,
        motion,
        easing,
        elevation,
        shape,
    }
} as const