import { Palettes } from "./modules/color";
import { ElevationLevels } from "./modules/elevation";
import { MotionDurations, MotionEasings } from "./modules/motion";
import { Shapes } from "./modules/shape";

const motion = {
    short1: MotionDurations.Short1,
    short2: MotionDurations.Short2,
    short3: MotionDurations.Short3,
    short4: MotionDurations.Short4,
    medium1: MotionDurations.Medium1,
    medium2: MotionDurations.Medium2,
    medium3: MotionDurations.Medium3,
    medium4: MotionDurations.Medium4,
    long1: MotionDurations.Long1,
    long2: MotionDurations.Long2,
    long3: MotionDurations.Long3,
    long4: MotionDurations.Long4,
    extraLong1: MotionDurations.ExtraLong1,
    extraLong2: MotionDurations.ExtraLong2,
    extraLong3: MotionDurations.ExtraLong3,
    extraLong4: MotionDurations.ExtraLong4,
} as const

const easing = {
    standard: MotionEasings.Standard,
    standardAccelerate: MotionEasings.StandardAccelerate,
    standardDecelerate: MotionEasings.StandardDecelerate,
    emphasized: MotionEasings.Emphasized,
    emphasizedAccelerate: MotionEasings.EmphasizedAccelerate,
    emphasizedDecelerate: MotionEasings.EmphasizedDecelerate,
    legacy: MotionEasings.Legacy,
    legacyAccelerate: MotionEasings.LegacyAccelerate,
    legacyDecelerate: MotionEasings.LegacyDecelerate,
    linear: MotionEasings.Linear,
} as const

const elevation = {
    level0: ElevationLevels.Level0,
    level1: ElevationLevels.Level1,
    level2: ElevationLevels.Level2,
    level3: ElevationLevels.Level3,
    level4: ElevationLevels.Level4,
    level5: ElevationLevels.Level5,
} as const

const shape = {
    full: Shapes.Full,
    extraLarge: Shapes.ExtraLarge,
    large: Shapes.Large,
    medium: Shapes.Medium,
    small: Shapes.Small,
    extraSmall: Shapes.ExtraSmall,
    none: Shapes.None,
} as const

const palette = {
    black: Palettes.Black,
    error0: Palettes.Error0,
    error10: Palettes.Error10,
    error100: Palettes.Error100,
    error20: Palettes.Error20,
    error30: Palettes.Error30,
    error40: Palettes.Error40,
    error50: Palettes.Error50,
    error60: Palettes.Error60,
    error70: Palettes.Error70,
    error80: Palettes.Error80,
    error90: Palettes.Error90,
    error95: Palettes.Error95,
    error99: Palettes.Error99,
    neutralVariant0: Palettes.NeutralVariant0,
    neutralVariant10: Palettes.NeutralVariant10,
    neutralVariant100: Palettes.NeutralVariant100,
    neutralVariant20: Palettes.NeutralVariant20,
    neutralVariant30: Palettes.NeutralVariant30,
    neutralVariant40: Palettes.NeutralVariant40,
    neutralVariant50: Palettes.NeutralVariant50,
    neutralVariant60: Palettes.NeutralVariant60,
    neutralVariant70: Palettes.NeutralVariant70,
    neutralVariant80: Palettes.NeutralVariant80,
    neutralVariant90: Palettes.NeutralVariant90,
    neutralVariant95: Palettes.NeutralVariant95,
    neutralVariant99: Palettes.NeutralVariant99,
    neutral0: Palettes.Neutral0,
    neutral10: Palettes.Neutral10,
    neutral100: Palettes.Neutral100,
    neutral12: Palettes.Neutral12,
    neutral17: Palettes.Neutral17,
    neutral20: Palettes.Neutral20,
    neutral22: Palettes.Neutral22,
    neutral24: Palettes.Neutral24,
    neutral30: Palettes.Neutral30,
    neutral4: Palettes.Neutral4,
    neutral40: Palettes.Neutral40,
    neutral50: Palettes.Neutral50,
    neutral6: Palettes.Neutral6,
    neutral60: Palettes.Neutral60,
    neutral70: Palettes.Neutral70,
    neutral80: Palettes.Neutral80,
    neutral87: Palettes.Neutral87,
    neutral90: Palettes.Neutral90,
    neutral92: Palettes.Neutral92,
    neutral94: Palettes.Neutral94,
    neutral95: Palettes.Neutral95,
    neutral96: Palettes.Neutral96,
    neutral98: Palettes.Neutral98,
    neutral99: Palettes.Neutral99,
    primary0: Palettes.Primary0,
    primary10: Palettes.Primary10,
    primary100: Palettes.Primary100,
    primary20: Palettes.Primary20,
    primary30: Palettes.Primary30,
    primary40: Palettes.Primary40,
    primary50: Palettes.Primary50,
    primary60: Palettes.Primary60,
    primary70: Palettes.Primary70,
    primary80: Palettes.Primary80,
    primary90: Palettes.Primary90,
    primary95: Palettes.Primary95,
    primary99: Palettes.Primary99,
    secondary0: Palettes.Secondary0,
    secondary10: Palettes.Secondary10,
    secondary100: Palettes.Secondary100,
    secondary20: Palettes.Secondary20,
    secondary30: Palettes.Secondary30,
    secondary40: Palettes.Secondary40,
    secondary50: Palettes.Secondary50,
    secondary60: Palettes.Secondary60,
    secondary70: Palettes.Secondary70,
    secondary80: Palettes.Secondary80,
    secondary90: Palettes.Secondary90,
    secondary95: Palettes.Secondary95,
    secondary99: Palettes.Secondary99,
    tertiary0: Palettes.Tertiary0,
    tertiary10: Palettes.Tertiary10,
    tertiary100: Palettes.Tertiary100,
    tertiary20: Palettes.Tertiary20,
    tertiary30: Palettes.Tertiary30,
    tertiary40: Palettes.Tertiary40,
    tertiary50: Palettes.Tertiary50,
    tertiary60: Palettes.Tertiary60,
    tertiary70: Palettes.Tertiary70,
    tertiary80: Palettes.Tertiary80,
    tertiary90: Palettes.Tertiary90,
    tertiary95: Palettes.Tertiary95,
    tertiary99: Palettes.Tertiary99,
    white: Palettes.White,
} as const

const color = {
    background: `light-dark(var(--md-sys-palette-neutral-98, #fef7ff), var(--md-sys-palette-neutral-6, #141218))`,
    error: `light-dark(var(--md-sys-palette-error-40, #b3261e), var(--md-sys-palette-error-80, #f2b8b5))`,
    errorContainer: `light-dark(var(--md-sys-palette-error-90, #f9dedc), var(--md-sys-palette-error-30, #8c1d18))`,
    inverseOnSurface: `light-dark(var(--md-sys-palette-neutral-95, #f5eff7), var(--md-sys-palette-neutral-20, #322f35))`,
    inversePrimary: `light-dark(var(--md-sys-palette-primary-80, #d0bcff), var(--md-sys-palette-primary-40, #6750a4))`,
    inverseSurface: `light-dark(var(--md-sys-palette-neutral-20, #322f35), var(--md-sys-palette-neutral-90, #e6e0e9))`,
    onBackground: `light-dark(var(--md-sys-palette-neutral-10, #1d1b20), var(--md-sys-palette-neutral-90, #e6e0e9))`,
    onError: `light-dark(var(--md-sys-palette-error-100, #fff), var(--md-sys-palette-error-20, #601410))`,
    onErrorContainer: `light-dark(var(--md-sys-palette-error-10, #410e0b), var(--md-sys-palette-error-90, #f9dedc))`,
    onPrimary: `light-dark(var(--md-sys-palette-primary-100, #fff), var(--md-sys-palette-primary-20, #381e72))`,
    onPrimaryContainer: `light-dark(var(--md-sys-palette-primary-10, #21005d), var(--md-sys-palette-primary-90, #eaddff))`,
    onPrimaryFixed: `var(--md-sys-palette-primary-10, #21005d)`,
    onPrimaryFixedVariant: `var(--md-sys-palette-primary-30, #4f378b)`,
    onSecondary: `light-dark(var(--md-sys-palette-secondary-100, #fff), var(--md-sys-palette-secondary-20, #332d41))`,
    onSecondaryContainer: `light-dark(var(--md-sys-palette-secondary-10, #1d192b), var(--md-sys-palette-secondary-90, #e8def8))`,
    onSecondaryFixed: `var(--md-sys-palette-secondary-10, #1d192b)`,
    onSecondaryFixedVariant: `var(--md-sys-palette-secondary-30, #4a4458)`,
    onSurface: `light-dark(var(--md-sys-palette-neutral-10, #1d1b20), var(--md-sys-palette-neutral-90, #e6e0e9))`,
    onSurfaceVariant: `light-dark(var(--md-sys-palette-neutral-variant-30, #49454f), var(--md-sys-palette-neutral-variant-80, #cac4d0))`,
    onTertiary: `light-dark(var(--md-sys-palette-tertiary-100, #fff), var(--md-sys-palette-tertiary-20, #492532))`,
    onTertiaryContainer: `light-dark(var(--md-sys-palette-tertiary-10, #31111d), var(--md-sys-palette-tertiary-90, #ffd8e4))`,
    onTertiaryFixed: `var(--md-sys-palette-tertiary-10, #31111d)`,
    onTertiaryFixedVariant: `var(--md-sys-palette-tertiary-30, #633b48)`,
    outline: `light-dark(var(--md-sys-palette-neutral-50, #79767d), var(--md-sys-palette-neutral-60, #938f96))`,
    outlineVariant: `light-dark(var(--md-sys-palette-neutral-variant-80, #cac4d0), var(--md-sys-palette-neutral-variant-30, #49454f))`,
    primary: `light-dark(var(--md-sys-palette-primary-40, #6750a4), var(--md-sys-palette-primary-80, #d0bcff))`,
    primaryContainer: `light-dark(var(--md-sys-palette-primary-90, #eaddff), var(--md-sys-palette-primary-30, #4f378b))`,
    primaryFixed: `var(--md-sys-palette-primary-90, #eaddff)`,
    primaryFixedDim: `var(--md-sys-palette-primary-80, #d0bcff)`,
    scrim: `var(--md-sys-palette-neutral-0, #000)`,
    secondary: `light-dark(var(--md-sys-palette-secondary-40, #625b71), var(--md-sys-palette-secondary-80, #ccc2dc))`,
    secondaryContainer: `light-dark(var(--md-sys-palette-secondary-90, #e8def8), var(--md-sys-palette-secondary-30, #4a4458))`,
    secondaryFixed: `var(--md-sys-palette-secondary-90, #e8def8)`,
    secondaryFixedDim: `var(--md-sys-palette-secondary-80, #ccc2dc)`,
    shadow: `var(--md-sys-palette-neutral-0, #000)`,
    surface: `light-dark(var(--md-sys-palette-neutral-98, #fef7ff), var(--md-sys-palette-neutral-6, #141218))`,
    surfaceBright: `light-dark(var(--md-sys-palette-neutral-98, #fef7ff), var(--md-sys-palette-neutral-24, #3b383e))`,
    surfaceContainer: `light-dark(var(--md-sys-palette-neutral-94, #f3edf7), var(--md-sys-palette-neutral-12, #211f26))`,
    surfaceContainerHigh: `light-dark(var(--md-sys-palette-neutral-92, #ece6f0), var(--md-sys-palette-neutral-17, #2b2930))`,
    surfaceContainerHighest: `light-dark(var(--md-sys-palette-neutral-90, #e6e0e9), var(--md-sys-palette-neutral-22, #36343b))`,
    surfaceContainerLow: `light-dark(var(--md-sys-palette-neutral-96, #f7f2fa), var(--md-sys-palette-neutral-10, #1d1b20))`,
    surfaceContainerLowest: `light-dark(var(--md-sys-palette-neutral-100, #fff), var(--md-sys-palette-neutral-4, #0f0d13))`,
    surfaceDim: `light-dark(var(--md-sys-palette-neutral-87, #ded8e1), var(--md-sys-palette-neutral-6, #141218))`,
    surfaceTint: `light-dark(var(--md-sys-palette-primary-40, #6750a4), var(--md-sys-palette-primary-80, #d0bcff))`,
    surfaceVariant: `light-dark(var(--md-sys-palette-neutral-variant-90, #e7e0ec), var(--md-sys-palette-neutral-variant-30, #49454f))`,
    tertiary: `light-dark(var(--md-sys-palette-tertiary-40, #7d5260), var(--md-sys-palette-tertiary-80, #efb8c8))`,
    tertiaryContainer: `light-dark(var(--md-sys-palette-tertiary-90, #ffd8e4), var(--md-sys-palette-tertiary-30, #633b48))`,
    tertiaryFixed: `var(--md-sys-palette-tertiary-90, #ffd8e4)`,
    tertiaryFixedDim: `var(--md-sys-palette-tertiary-80, #efb8c8)`,
} as const

export const md = {
    sys: {
        color,
        palette,
        motion,
        easing,
        elevation,
        shape,
    }
} as const